"use client";

import { useState } from "react";

// LinkedIn share button. LinkedIn's share-offsite intent auto-reads OG tags
// from the target URL, so the post's <meta og:image>, og:title, og:description
// (already generated by buildMetadata + the dynamic /opengraph-image route)
// become the preview card automatically. We just open the intent URL.
//
// For "twitter-style" pre-filled text, LinkedIn no longer supports a `summary`
// param in the standard share endpoint — the preview card is the pitch.

export function ShareLinkedIn({
  url,
  title,
  locale = "es",
}: {
  url: string;
  title?: string;
  locale?: "es" | "pt";
}) {
  const [copied, setCopied] = useState(false);
  const shareUrl = `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(url)}`;

  const labels = {
    es: { share: "Compartir en LinkedIn", copy: "Copiar enlace", copied: "¡Copiado!" },
    pt: { share: "Compartilhar no LinkedIn", copy: "Copiar link", copied: "Copiado!" },
  }[locale];

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(url);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      /* ignore */
    }
  };

  return (
    <div className="mt-6 flex flex-wrap items-center gap-2">
      <a
        href={shareUrl}
        target="_blank"
        rel="noopener noreferrer"
        aria-label={labels.share}
        className="inline-flex items-center gap-2 rounded-full border border-[color:var(--color-border)] bg-[color:var(--color-surface)] px-4 py-2 text-sm font-semibold text-[color:var(--color-foreground)] transition hover:border-[color:var(--color-mint-500)] hover:text-[color:var(--color-mint-700)]"
      >
        <svg viewBox="0 0 24 24" className="h-4 w-4" fill="currentColor" aria-hidden>
          <path d="M20.45 20.45h-3.55v-5.57c0-1.33-.03-3.04-1.85-3.04-1.85 0-2.14 1.45-2.14 2.94v5.67H9.36V9h3.41v1.56h.05c.48-.9 1.63-1.85 3.36-1.85 3.6 0 4.27 2.37 4.27 5.45v6.29ZM5.34 7.43a2.06 2.06 0 1 1 0-4.12 2.06 2.06 0 0 1 0 4.12ZM7.12 20.45H3.56V9h3.56v11.45ZM22.22 0H1.77C.79 0 0 .77 0 1.72v20.56C0 23.23.79 24 1.77 24h20.45c.98 0 1.78-.77 1.78-1.72V1.72C24 .77 23.2 0 22.22 0Z" />
        </svg>
        {labels.share}
      </a>
      <button
        type="button"
        onClick={copy}
        aria-label={labels.copy}
        className="inline-flex items-center gap-2 rounded-full border border-[color:var(--color-border)] bg-[color:var(--color-surface)] px-4 py-2 text-sm font-semibold text-[color:var(--color-muted)] transition hover:border-[color:var(--color-mint-500)] hover:text-[color:var(--color-foreground)]"
      >
        <svg viewBox="0 0 24 24" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden>
          {copied ? (
            <path d="M5 12l5 5 9-11" />
          ) : (
            <>
              <rect x="9" y="9" width="11" height="11" rx="2" />
              <path d="M5 15V5a2 2 0 0 1 2-2h10" />
            </>
          )}
        </svg>
        {copied ? labels.copied : labels.copy}
      </button>
      {title && <span className="sr-only">{title}</span>}
    </div>
  );
}
