// AUTO-GENERATED by scripts/gen-post-locales.mjs — do not edit by hand.
// Which locales actually publish each blog slug. Consumed by the language
// switcher (a client component) so it never links to an untranslated post.
import type { Locale } from "@/lib/i18n";

export const postLocales: Readonly<Record<string, Locale[]>> = {
  "aprende-a-programar-desde-cero": [
    "es",
    "pt",
    "en"
  ],
  "automatizacion-bim-trujillo-la-libertad": [
    "es"
  ],
  "automatizar-civil-3d-guia-completa": [
    "es",
    "pt",
    "en"
  ],
  "automatizar-metrados-cubicaciones-civil-3d": [
    "es"
  ],
  "crear-plugin-civil-3d-con-claude-code-sin-programar": [
    "es",
    "pt",
    "en"
  ],
  "cuanto-cuesta-un-add-in-revit-civil-3d": [
    "es",
    "pt",
    "en"
  ],
  "deja-de-usar-excel-y-perder-horas": [
    "es",
    "pt",
    "en"
  ],
  "desarrollo-add-ins-revit-civil-3d-guia-completa": [
    "es",
    "pt",
    "en"
  ],
  "dynamo-csharp-con-ia-claude": [
    "es",
    "pt",
    "en"
  ],
  "dynamo-vs-csharp-civil3d-revit": [
    "es",
    "pt",
    "en"
  ],
  "estandarizar-procesos-bim-empresa": [
    "es",
    "pt",
    "en"
  ],
  "expediente-tecnico-observaciones-reducir": [
    "es"
  ],
  "guia-vibe-coding-para-empezar": [
    "es",
    "pt",
    "en"
  ],
  "plan-bim-peru-obligatorio-guia-empresas": [
    "es"
  ],
  "programacion-para-ingenieros-civiles": [
    "es",
    "pt",
    "en"
  ],
  "ramas-ingenieria-sistemas-especializaciones": [
    "es",
    "pt",
    "en"
  ],
  "reprocesos-obra-costo-oculto": [
    "es",
    "pt",
    "en"
  ],
  "revit-api-espanol-primeros-pasos": [
    "es"
  ]
};
